# Generated by Django 4.0.3 on 2022-03-29 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSubscription',
            fields=[
                ('card', models.OneToOneField(db_column='card', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.card')),
                ('expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'card_subscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('sub_id', models.IntegerField(db_column='sub_ID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.TextField()),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'subscription',
                'managed': False,
            },
        ),
    ]
