# Generated by Django 4.0.3 on 2022-04-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_cardsubscription_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAction',
            fields=[
                ('transaction_id', models.CharField(db_column='transaction_ID', max_length=256, primary_key=True, serialize=False)),
                ('new_amount', models.IntegerField()),
                ('charge', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('bus_number', models.IntegerField(blank=True, null=True)),
                ('verification', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'card_action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionTypes',
            fields=[
                ('type_id', models.IntegerField(db_column='type_ID', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'transaction_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TravelZone',
            fields=[
                ('zone_id', models.IntegerField(db_column='zone_ID', primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=256)),
                ('ride_charge', models.IntegerField()),
            ],
            options={
                'db_table': 'travel_zone',
                'managed': False,
            },
        ),
    ]
